
/*
 * 
 */

package com.ambientideas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2
 * Sun Mar 29 23:00:51 MDT 2009
 * Generated source version: 2.2
 * 
 */


@WebServiceClient(name = "carShow", 
                  wsdlLocation = "http://localhost:8080/JackedUpApp2/services/carShow?wsdl",
                  targetNamespace = "http://DefaultNamespace") 
public class CarShow_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://DefaultNamespace", "carShow");
    public final static QName CarShowHttpPort = new QName("http://DefaultNamespace", "carShowHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/JackedUpApp2/services/carShow?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/JackedUpApp2/services/carShow?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CarShow_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CarShow_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarShow_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns CarShow
     */
    @WebEndpoint(name = "carShowHttpPort")
    public CarShow getCarShowHttpPort() {
        return super.getPort(CarShowHttpPort, CarShow.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarShow
     */
    @WebEndpoint(name = "carShowHttpPort")
    public CarShow getCarShowHttpPort(WebServiceFeature... features) {
        return super.getPort(CarShowHttpPort, CarShow.class, features);
    }

}
