package com.ambientideas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2
 * Sun Mar 29 23:00:51 MDT 2009
 * Generated source version: 2.2
 * 
 */
 
@WebService(targetNamespace = "http://DefaultNamespace", name = "carShow")
@XmlSeeAlso({ObjectFactory.class})
public interface CarShow {

    @WebResult(name = "out", targetNamespace = "http://DefaultNamespace")
    @RequestWrapper(localName = "getAllCarShows", targetNamespace = "http://DefaultNamespace", className = "com.ambientideas.GetAllCarShows")
    @ResponseWrapper(localName = "getAllCarShowsResponse", targetNamespace = "http://DefaultNamespace", className = "com.ambientideas.GetAllCarShowsResponse")
    @WebMethod
    public com.ambientideas.ArrayOfCarShow getAllCarShows();

    @WebResult(name = "out", targetNamespace = "http://DefaultNamespace")
    @RequestWrapper(localName = "getAllCarShowsAsArray", targetNamespace = "http://DefaultNamespace", className = "com.ambientideas.GetAllCarShowsAsArray")
    @ResponseWrapper(localName = "getAllCarShowsAsArrayResponse", targetNamespace = "http://DefaultNamespace", className = "com.ambientideas.GetAllCarShowsAsArrayResponse")
    @WebMethod
    public com.ambientideas.ArrayOfCarShow getAllCarShowsAsArray();

    @WebResult(name = "out", targetNamespace = "http://DefaultNamespace")
    @RequestWrapper(localName = "getCarShow", targetNamespace = "http://DefaultNamespace", className = "com.ambientideas.GetCarShow")
    @ResponseWrapper(localName = "getCarShowResponse", targetNamespace = "http://DefaultNamespace", className = "com.ambientideas.GetCarShowResponse")
    @WebMethod
    public com.ambientideas.CarShow_Type getCarShow(
        @WebParam(name = "in0", targetNamespace = "http://DefaultNamespace")
        int in0
    );

    @WebResult(name = "out", targetNamespace = "http://DefaultNamespace")
    @RequestWrapper(localName = "isValidCarShow", targetNamespace = "http://DefaultNamespace", className = "com.ambientideas.IsValidCarShow")
    @ResponseWrapper(localName = "isValidCarShowResponse", targetNamespace = "http://DefaultNamespace", className = "com.ambientideas.IsValidCarShowResponse")
    @WebMethod
    public boolean isValidCarShow(
        @WebParam(name = "in0", targetNamespace = "http://DefaultNamespace")
        int in0
    );
}
