
package com.ambientideas;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2
 * Sun Mar 29 23:00:51 MDT 2009
 * Generated source version: 2.2
 * 
 */
 
public class CarShow_CarShowHttpPort_Server{

    protected CarShow_CarShowHttpPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new CarShowImpl();
        String address = "http://localhost:8080/JackedUpApp2/services/carShow";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new CarShow_CarShowHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
