
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ambientideas;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2
 * Sun Mar 29 23:00:51 MDT 2009
 * Generated source version: 2.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "carShow",
                      portName = "carShowHttpPort",
                      targetNamespace = "http://DefaultNamespace",
                      wsdlLocation = "http://localhost:8080/JackedUpApp2/services/carShow?wsdl",
                      endpointInterface = "com.ambientideas.CarShow")
                      
public class CarShowImpl implements CarShow {

    private static final Logger LOG = Logger.getLogger(CarShowImpl.class.getName());

    /* (non-Javadoc)
     * @see com.ambientideas.CarShow#getAllCarShows(*
     */
    public com.ambientideas.ArrayOfCarShow getAllCarShows() { 
        LOG.info("Executing operation getAllCarShows");
        try {
            com.ambientideas.ArrayOfCarShow _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ambientideas.CarShow#getAllCarShowsAsArray(*
     */
    public com.ambientideas.ArrayOfCarShow getAllCarShowsAsArray() { 
        LOG.info("Executing operation getAllCarShowsAsArray");
        try {
            com.ambientideas.ArrayOfCarShow _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ambientideas.CarShow#getCarShow(int  in0 )*
     */
    public com.ambientideas.CarShow_Type getCarShow(int in0) { 
        LOG.info("Executing operation getCarShow");
        System.out.println(in0);
        try {
            com.ambientideas.CarShow_Type _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ambientideas.CarShow#isValidCarShow(int  in0 )*
     */
    public boolean isValidCarShow(int in0) { 
        LOG.info("Executing operation isValidCarShow");
        System.out.println(in0);
        try {
            boolean _return = false;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
